tests: uncouple BadConfigTests from ConfigTests
The BadConfigTests class inherited from ConfigTests to re-use the
setUp() and tearDown() infrastructure (which just brackets the test case
with log messages).

This leads to spurious errors since it also inherits all the `test_*`
methods from the superclass.

When replacing BadConfigTests.test_load_boom_config_default with
BadConfigTests.test_load_boom_config_invalid_raises exposes the
inherited BadConfigTests.test_load_boom_config_default (since it is no
longer overriden in the child class): this then fails since the fixture
is incorrect for this test method:

FAILED tests/test_config.py::BadConfigTests::test_load_boom_config_default - ValueError: Missing 'global' section in /home/breeves/src/git/boom-boot/tests/sandbox/boot/boom/boom.conf

Avoid this unwanted inheritance and clean up the definition of the
configuration test classes: factor out the common code from ConfigTests
into and abstract base, ConfigTestsBase (which defines no test_*
methods), and have both ConfigTests and BadConfigTests inherit from this
common class.

Related: #122
Resolves: #124

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>